### ISSUE TITLE
Which is the right threshold value?

### ISSUE THREAD

**Issue by Aliax3** [benjjneb/decontam#102]
First of all, thank you very much for creating `Decontam`, it is an amazing package!

Secondly, I need help in regards to a couple of questions which arose after using it. Before going into that, let me explain my data: I collected faecal samples from several captive feline species in order to find out which pathogenic species do circulate amongst these animals, as well as their microbial gut species. Faeces were collected after being deposited by the animals, so I do expect environmental contamination coming from being left on the ground, in the open-air, for hours (basically until their keepers could access their cages in the morning for cleaning). In an attempt to control further DNA contamination, the samples’ DNA was isolated using a kit optimised for next-generation sequencing and proper lab practises were followed to reduce as much as I could any contaminants coming from this process, but I assume I can expect contaminants even after all that. After the extraction, the samples were sent for Shotgun Metagenomic Sequencing at an external company, which also performed the relevant bioinformatic analyses to finally send back to us all the reads’ counts per species in each sample.
 
It is in this dataset that I applied Decontam’s package, together with the DNA concentration provided by the Qubit readings reported by the company prior to the sequencing. I did not send negative controls due to budgetary constraints, so I do need to rely only on the results of the frequencies. I initially applied the default threshold value, and plotted the P value coming out from `Decontam` (please find the plot below). According to [Davis et al.'s paper (2018)](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0605-2), I should be able to find out which is the right threshold to apply by looking at this plot, but I have to admit that I am clueless on which one to choose, since it does not look similar to the two examples shown in the paper. Therefore:

- Which would be the right threshold to apply and why?
- Would it be correct to assume this package does show the contaminants coming only from the laboratory part, and not the environmental part (whilst being on the ground)? Based on this assumption, after removing the species detected as contaminants by `Decontam`, I am planning to further remove any species which do not qualify as species which can be found in animals (i.e., everything which is not a microbial gut species or a pathogen)

![Rplot](https://user-images.githubusercontent.com/91933577/135962852-e59dec6f-794a-45ef-a69d-c92b79343ee7.png)

**Comment by benjjneb** [comment]
> Would it be correct to assume this package does show the contaminants coming only from the laboratory part, and not the environmental part (whilst being on the ground)?

Correct, at least in your case where you are relying on the frequency method and have no sampling-instrument controls.

> Based on this assumption, after removing the species detected as contaminants by Decontam, I am planning to further remove any species which do not qualify as species which can be found in animals (i.e., everything which is not a microbial gut species or a pathogen)

That can be OK, but I'm not sure I would use to heavy a hand here, because...

> Which would be the right threshold to apply and why?

I don't know about cats specifically, but feces typically has a very high microbial load. This means that contamination is a minor issue in most fecal studies. The score spectrum you showed here is consistent with that. There is not a bimodal distribution of high-scoring non-contaminants and low-scoring contminants. There is just a nearly monotonic decrease in the frequency as scores get lower. This is consistent with there being little to no contamination in your sequencing.

There is not one perfect threshold, but based on what you've shown here, I would be comfortable picking any threshold from 0.1 to 0.4. I would pick a more stringent (lower) threshold if I wanted to err on the side of only removing species I was sure were contaminants, and a less stringent (higher) threshold if I wanted to be more confident I had removed most contaminants.

**Comment by Aliax3** [comment]
Thank you very much @benjjneb for your help! I will proceed as suggested then 😊
