### ISSUE TITLE
Clarification on DNA quantitation

### ISSUE THREAD

**Issue by cyklee** [benjjneb/decontam#24]
Hi, thanks for making decontam available. Just a quick feedback regarding the vignette

I thought "DNA quantitation" (particularly in the line below) could use a little clarification:

> DNA quantitation (concentration of DNA) measured prior to mixing samples into equimolar ratios for sequencing

While I understand the library processing steps for Illumina sequencing, I wasn't entirely certain if you didn't mean DNA quantitation right after DNA extraction, so I dug into the preprint:

> Amplicons were purified, DNA-quantitated using the PicoGreen fluorescence-based Quant-iT dsDNA...

Ok, I've gathered that you meant DNA quantitation *after* the PCR step.

Perhaps others may trip over this and accidentally used the DNA quant before they send their samples off for sequencing, instead of requesting for post-PCR amplicon DNA quantification from their sequencing supplier.

Kind regards,
Kevin

**Comment by benjjneb** [comment]
Thanks for that feedback. We think, and have some evidence, that DNA quantitation at either step will work, but agree this needs to be clarified in the manuscript. It is true that the largest fraction of our testing has used the DNA quantitation directly prior to sequencing, largely because this is the most commonly collected quantitation data.

Agree this is important to clarify in the vignette though!

**Comment by waleadebayo** [comment]
Thanks for the good work : finally putting what "microbiomists" have
discussed and discussed for half a decade into a systematic tool!!

It might be good to have a bar plot showing average prevalence in the two
groups for the prevalence section. Just for ease of interpretation.

 It might also be good to briefly give idea of the structure of
"MClite.rds" data used in the vignette because for a newbie who does not
know how to extract info from a phyloseq object, visualising some variables
maybe difficult.

For instance, within the Sample_or_Control variable, I for instance thought
the factor levels will be "control" or "sample". And the element it takes
while determining prevalence i.e. " Control Sample " made me think its a
combination until I examined the phyloseq object structure. The plotting
along the axes may help reveal this earlier, but maybe a table snapshot of
sample data in MClite.rds at the beginning helps.

Thanks a lot
