### ISSUE TITLE
Decontam w/ just one control?

### ISSUE THREAD

**Issue by andrebolerbarros** [benjjneb/decontam#38]
I'm now starting to use the package in the analysis of 16s amplicon sequencing. I've read through the paper and the tutorial and it sounds very useful for me indeed!

However, the data that I've now to analyse only contains one control sample (negative) per set of samples. Although I can still work with the frequency method; however, I was wondering if there is an alternative to the prevalence method in this conditions.

These are indeed far from ideal, I know but, I'm just trying to see if I can still do some contaminant filtering in these samples. 

Thanks!

**Comment by benjjneb** [comment]
No, the prevalence method is not useful with just a single negative control, and in general I would recommend caution in removing features based on one negative control because of the possibility of cross-contamination putting real ASVs into negative controls. The way I would use a single negative controls would be just as a post-hoc check on any conclusions of my main analysis. E.g. if I find ASV22 to be highly predictive of my condition of interest, I would check if its also in that control and at least mention it in the text if it was.

The frequency method should work just fine for you though, and is effective all on its own.

**Comment by andrebolerbarros** [comment]
Thanks @benjjneb for the swift answer!
