### ISSUE TITLE
isNotContaminant

### ISSUE THREAD

**Issue by bmillerlab** [benjjneb/decontam#49]
Hello, I am working with low biomass samples and would like to use isNotContaminant.  I am not good in R and though I can run isContaminant using decontam I can't get isNotContaminant to work for me correctly.  The data frame I get does not include the frequency information.  I have tried to find a tutorial like the one for isContaminant that shows the series of commands to figure out how to fix this problem, but I can't seem to find one.  Does such a tutorial exist?  If not, is there at least someplace I can get more information on the correct series of commands to use - right now I can only find this page with the most basic command: https://rdrr.io/bioc/decontam/man/isNotContaminant.html .  And, for some reason the example won't run on that page!

Thank you.

**Comment by benjjneb** [comment]
> The data frame I get does not include the frequency information.

That is intentional. `isNotContaminant` only makes use of prevalence information (i.e. the patterns of presence/absence across samples and controls). This is because the most extreme scores based on frequency information don't actually identify the best non-contaminant candidates, but rather pick out taxa that by chance were most precisely equal in frequency across samples.

That said, you can still use the frequency scores returned by `isContaminant` to pick out the set of taxa that are more likely to be non-contaminants (i.e. the high-score mode).

**Comment by lisas0704** [comment]
Hi, 
I tried to use isNotContaminant for my low biomass samples, but I have problems getting the code to run. 
I tried to use the tutorial code for isContaminant (prevalence), but I can't get a result. Is isNotContaminant using another kind of code?

Cheers,
Lisa

**Comment by benjjneb** [comment]
> Is isNotContaminant using another kind of code?

No, it's a wrapper around the same core code that `isContaminant` uses. Note that only the `"prevalence"` method is included in `isNotContaminant` though, the `"frequency"` method is not.
