### ISSUE TITLE
Plot_frequency y-axis

### ISSUE THREAD

**Issue by mkeady2** [benjjneb/decontam#62]
Hi,
Is it possible to change the axis on the frequency plot of contaminants? The plots I am getting do not quite resemble the examples. It looks like there are points below the black dashed line that are out of view. I have tried to use ylim but that doesn't seem to work. 

Thanks,
![decontam Rplot](https://user-images.githubusercontent.com/57913918/69076718-0b0f8400-0a02-11ea-9349-d975f238d46b.png)
![decontamASV plots](https://user-images.githubusercontent.com/57913918/69076719-0b0f8400-0a02-11ea-83be-5b1be460a7ed.png)

Mia

**Comment by benjjneb** [comment]
You can change any aspect of the plot through normal ggplot2 mechanisms.

The points at the bottom of the plot are the zero-frequency values, which are negative `Inf` on the log-scale plot. The default way in which ggplot2 shows those `-Inf` values is to put them half-off the bottom of the plot.

**Comment by mkeady2** [comment]
Okay - thank you for the quick response. I figured it could use ggplot2 format.
Why does your sample data set has so many more points?

**Comment by benjjneb** [comment]
> Why does your sample data set has so many more points?

The number of points is the number of samples in which each ASV appears in non-zero frequency. In our example dataset, many of the abundant contaminant ASVs appeared in a lot of samples. This is probably because it had a lot of samples, and because it was a lower biomass sample type in which contaminants will be more abundant than in e.g. stool samples.

**Comment by mkeady2** [comment]
Great - thank you for your help.
