### ISSUE TITLE
Adjusting the false discovery rate in frequency mode

### ISSUE THREAD

**Issue by nickilott** [benjjneb/decontam#69]
Hi,

Thanks for the great package, I am finding it very useful. I was wondering if decontam controls the false discovery rate (I am currently just using the frequency method). After I run decontam I get a p-value (p.freq) distribution that looks like the attached. It seems to me that there is no evidence for contamination from this although some ASVs are called at p < 0.05. Is it appropriate to apply p.adjust to the p.freq column?

Thanks for your help

**Comment by nickilott** [comment]
Sorry here is the p-value distribution
![decontam_histogram](https://user-images.githubusercontent.com/5478648/74749564-3d7b8800-5262-11ea-8ce8-98215cd4bd78.png)

**Comment by benjjneb** [comment]
> I was wondering if decontam controls the false discovery rate (I am currently just using the frequency method). After I run decontam I get a p-value (p.freq) distribution that looks like the attached. It seems to me that there is no evidence for contamination from this although some ASVs are called at p < 0.05. Is it appropriate to apply p.adjust to the p.freq column?

No, because the score ('p') is not a p-value. Sorry for the (in retrospect, very) bad choice of variable name for the score, but to reiterate, it should not be considered to be a p-value, i.e. it has no associate with a specific FDR.

It should be interpreted as a score, that will tend to be low from the contaminant portion of the mixture, and high from the non-contaminant portion of the mixture. The method is then a classificaiton method that tries to accurately classify the taxa into each part of the mixture.

When I look at your score distribution, I see the potential suggestion of a mixture of a low-score mode <0.20, and a high score mode (~0.4-1). So, eyeballing, a threshold around 0.2 might effectively classify the modes. However, it is not completely obvious here that there is a significant contaminant mode (as is sometimes-often the case because sources of contamination are so heterogeneous) so there is some ambiguity that could be resolved either by the relative importance to your subsequent analysis of removing contaminants versus maximizing the number of features in the table, and potentially more in depth analysis of the candidate contaminants.

**Comment by nickilott** [comment]
Thanks for the quick response and help with the interpretation of the scores! Thanks again for the software!

Nick
