### ISSUE TITLE
Individual blanks/control samples

### ISSUE THREAD

**Issue by st01565** [benjjneb/decontam#9]
For our low-biomass (lung) study we have individual negative control samples. That is - all participants were sampled by at least three different methods and one negative control followed the procedural samples through the extraction, PCR and sequencing process (Illumina, paired end, dual indexing,  V3-V4, 2*300bp).

Would you do any specific amendments to the decontam tutorial for this project or would you just run it as shown in the excellent tutorial?

Cheers,

Rune

**Comment by benjjneb** [comment]
If using the `"prevalence"` method, I would probably run it as in the tutorial where all the negative control samples are considered as falling into the same category. This is because the gain in statistical power to identify contaminants from having multiple negative control samples is going to be greater than the potential benefit of matching negative controls to specific individuals.

Is there a reason to think that the negative controls associated with each individual will be quite different? One quick check on that I might do is to perform two ordinations of the samples: one colored by negative control or not, and the other colored by subject. My expectation would be that the negative controls group together with each other, more than they group with their associated subject.

**Comment by st01565** [comment]
Thank you!
The reason for including controls per individual participant was that the sampling fluid (instilled and suctioned from the lung) had to be exchanged daily, and we only examined one or two participants per day. I also have to admit that when we designed the study (and performed the sequencing) we were not that well schooled in the methods, and I think this might be one of the things that I would have done differently today. 

One follow-up:
What would be your take on how to handle possible cross-talk, when applying the prevalence method. In the preprint of you decontam manuscript you mention that quality filtering probably would take care of most of this issue. And I've tried reading the Wright and Vetsigian BMC Genomics -paper from 2016. But, I failed to understand how to perform this in practice. Our sequencing facility delivers demultiplexed files, without the index sequences. 

I really appreciate your answer!

Cheers,

Rune

**Comment by benjjneb** [comment]
> What would be your take on how to handle possible cross-talk, when applying the prevalence method.

Cross-talk is not a solved problem yet, sadly. As we noted, the decontam method is not ideal for detecting cross-talk on the sequencer, as that kind of contamination has a different statistical signature.

> And I've tried reading the Wright and Vetsigian BMC Genomics -paper from 2016. But, I failed to understand how to perform this in practice.

Right now I am not aware of an implementation available in practice, unfortunately, but maybe @digitalwright might know more? IMO a follow-up on that work, both exploring the signal they reported in additional datasets and developing a usable implementation for easily filtering based on index reads could be quite impactful.

**Comment by digitalwright** [comment]
Indeed, cross-talk is not a solved problem.  Experimentally you can mitigate (but not eliminate) it in a variety of ways: (1) reducing free adapter that goes into the sequencing reaction (e.g., through size selection), (2) using unique dual index sequences for every sample, and (3) other strategies (e.g., see a recent paper [here](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-4428-5)).

After sequencing, you can greatly lower the rate of cross-talk by quality filtering ALL of your reads.  This is what we showed in [Wright and Vetsigian](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3217-x) (2016).  We have observed this for many different sequencing experiments, although we only focus on one in the paper.

> I've tried reading the Wright and Vetsigian BMC Genomics -paper from 2016. But, I failed to understand how to perform this in practice.

Regarding @st01565's comment, you first need to tell Illumina's bcl2fastq program to output all read files rather than only the main read(s).  This is not standard practice, but it is as simple as setting an input flag.  Then, once you have the fastq file(s), you read in each index file and quality filter it based on the average quality score.  If either index sequence does not pass quality filtering then you reject the associated read(s) as well.  In essence, it is nearly as simple as quality filtering your main read(s), but you need to do it on every read and reject the main read(s) when the index read(s) do not pass filter.

The question of what quality score to use as the cutoff is a little more difficult to answer.  You could simply use the same quality score threshold that we reported in the paper, or you could follow our strategy for optimizing the threshold (i.e., Fig. 5 in the paper).  If you take the latter approach then you need to have Illumina demultiplex virtual samples that belong to missing index combinations.  While you would expect to observe zero reads for these samples, you will probably observe some level of cross-talk.  You can set a quality score threshold that largely eliminates this cross-talk.  Note that this optimization approach requires dual-index sequencing, as well as omission of some of the index combinations.

> developing a usable implementation for easily filtering based on index reads could be quite impactful.

Regarding @benjjneb's comment, I agree in principle that this would be useful.  However, I have not taken this route because the above filtering method is so straightforward to implement.  That is, if you can filter one read then you can probably filter more than one, which is all we are saying you should do.  I think it is more about (i) making index quality filtering part standard practice and (ii) getting the index reads demultiplexed using Illumina's bcl2fastq program.  Unfortunately this requires non-default Illumina parameters, so often the user does not have the fastq files that would allow us to mitigate cross-talk using our method.  Ideally the index fastq files would be added to repositories (e.g., SRA) as standard practice.

I hope this helps to clarify the cross-talk issue.  IMO Illumina could take a more active role in addressing this more "globally", and they have made some indications that they might do so in the future.
