### ISSUE TITLE
Removing zeroes

### ISSUE THREAD

**Issue by andrewjmc** [benjjneb/decontam#97]
Thanks for this amazingly useful piece of software. I appreciate that the frequency and prevalence methods take different approaches to the data, and they can be combined. I hadn't appreciated until today that zeroes are dropped in the frequency based approach. Would it be feasible or advisable to include them by adding (say) the minimum non-zero value for each feature to all entries, so the log can be taken?

**Comment by benjjneb** [comment]
The model fitting in decontam is very simple, it is just a linear model (with a fixed slope!) being fit to log-transformed data. Thus, we determined it was better to omit zeros rather than try to introduce pseudo-counts or pseudo-frequencies. The reason for this is that the difference between zero and any pseudo-frequency in log-space is very large (infiinite actually), and much bigger than the range in the data itself. Thus, imperfect choices of pseudo-frequencies can really throw off the modeling.

The best solution would be a slighly more sophisticated modeling approach that handles zeros as "below limit of detection", but that's not on the horizon at least near-term.

**Comment by andrewjmc** [comment]
This seems fair.

I think in my use-case with kraken2/bracken read counts from reasonably high depth data, and multiple orders of magnitude variation in effective biomass (bacterial proportion x DNA conc), it really feels more reasonable to impute values (e.g. half the minimum, as in MaAsLin2). This is because the gap between the minimum value and zero is usually very much smaller than the range of non-zero values.

Interestingly, when I replaced zeroes in this way, no new contaminants were detected, but about three quarters of p<=0.05 contaminants were lost (though these were the low abundance ones as the total contaminant proportions barely shifted). Since for my purposes I care most about getting accurate relative abundances for the non-contaminants, rather than necessarily knowing all remaining organisms are not contaminants, this is probably fine. I was a little surprised though, since I expected the "imputation" would increase the power!
